### ISSUE TITLE
Add a --verbose flag for the progress bar to display each downloaded package on the fly.

### ISSUE THREAD

**Issue by HerManNav** [UB-Quantic/pypickup#26]

**Comment by mofeing** [comment]
A good idea is to use 2-nested progress bar instead: The top one for total progress (#downloaded files / #total packages) and the bottom one for the current downloading.

**Comment by HerManNav** [comment]
> A good idea is to use 2-nested progress bar instead: The top one for total progress (#downloaded files / #total packages) and the bottom one for the current downloading.

Yeah, that's the idea : ))
